# -*- coding: utf-8 -*-
"""A1 Student Code.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ot4ePnixTFe1JUq6mfbKfCc2rlAtRjyX
"""

import pandas as pd
import numpy as np
from tensorflow.keras.utils import to_categorical
import os

os.chdir('C:\\Users\ASUS\Downloads\Deep Learning')
"""###Read in data
If using Google Colab, you must first upload the file to the temporary storage. In the left panel click the file image -> click on file with up arrow 'upload to session storage' -> upload both train and test files (can take a couple minutes).
If using your personal computer, include location (e.g., 'C:/Files.../A1 - FashionMNIST - Train.csv')
"""

df_train = pd.read_csv('A1 - FashionMNIST - Train.csv')
train_labels = df_train['label'].values
train_labels = to_categorical(train_labels)
train_images = df_train.values[:,1:]
train_images = train_images.astype('float32') / 255
del df_train

df_test = pd.read_csv('A1 - FashionMNIST - Test.csv')
test_images = df_test.values[:,1:]
test_images = test_images.astype('float32') 
del df_test

train_images[:1]
test_images[:1]
"""### Run your model"""

# Example model (you must set tf and np random seeds for final model before you build it like in this example)
import tensorflow as tf
import tensorflow.keras as keras

tf.random.set_seed(31415)
np.random.seed(31415)

mymodel = keras.models.Sequential([
    keras.layers.Input(shape=(28*28,)),
    keras.layers.Dropout(0.2),
    keras.layers.Dense(128, activation='relu', kernel_initializer='he_uniform'),
    keras.layers.Dropout(0.2),
    keras.layers.Dense(128, activation='relu', kernel_initializer='he_uniform'),
    keras.layers.Dropout(0.2),
    keras.layers.Dense(10, activation="softmax")
    ])

print(mymodel.summary())

opt = keras.optimizers.Adam(lr=0.005, beta_1=0.95, beta_2=0.995)
mymodel.compile(optimizer=opt,
                loss='categorical_crossentropy',
                metrics=['accuracy'])
mymodel_hist = mymodel.fit(train_images, train_labels, epochs=10, batch_size=128)
"""### Create your predictions for the test data"""

df_test_labels_2000 = pd.read_csv('A1 - FashionMNIST - Test - First 2000 Labels.csv')
test_lables_2000 = df_test_labels_2000.values[:,1]
temp_predictions = mymodel.predict(test_images)
temp_predictions = np.argmax(temp_predictions,axis=1)[:2000]

print(np.sum(temp_predictions==test_lables_2000)/2000)
# Create Predictions
test_predictions = mymodel.predict(test_images)
print('Test matrix is the right shape (10000, 10)?: ', np.array_equal(test_predictions.shape, (10000, 10)))
test_predictions[1:]
"""### Output Predictions to a .csv file"""

# Output data to csv file
studentid = '2020730510'
df_out = pd.DataFrame(test_predictions)
df_out.to_csv('predictions_' + studentid + '.csv')
#df_out.to_csv('C:/FILE_FOLDER_LOCATION/predictions_' + studentid + '.csv')

"""Note: Google Colab users, you can now download the file to your personal computer by selecting download from the menu on the right (click 3 dots on right) when highlighting file."""